AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'Rakefile'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Exclude:
    - 'spec/rails_helper.rb'
    - 'Gemfile'

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 125

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'
