name: table_check_project
services:
  mongo:
    image: mongo:7.0.15
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
      - mongo_data:/data/db
      - ./mongo.key:/data/mongo.key:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLSET: rs0
    command: ["--replSet", "rs0", "--keyFile", "/data/mongo.key", "--bind_ip_all"]
    healthcheck:
      test: mongosh -u root -p root --authenticationDatabase admin --eval "try { rs.status() } catch (err) { rs.initiate({_id:'rs0', members:[{_id:0, host:'localhost:27017'}]}) }"
      interval: 2s
      timeout: 2s
      start_period: 2s
      start_interval: 1s
      retries: 10

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  mongo_data: {}
